name: quizzer_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-202.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
